# Configuration script for use with continuous integration service travis-ci.org

language: cpp

dist: bionic

matrix:
  include:
    # Python library Ubuntu 18.04
    - os: linux
      compiler: gcc
      addons: &gcc6
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'python3', 'libboost-python-dev', 'libboost-numpy-dev']
      env: BADGE=linux BUILD_TYPE="RELEASE" XCSF_PYLIB="ON"

    # Python library OSX
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      env: BADGE=osx BUILD_TYPE="RELEASE" XCSF_PYLIB="ON"

script:
  - cd "${TRAVIS_BUILD_DIR}/build"
  - |
    if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
      brew install llvm
      brew install libomp
      brew install cmake || brew upgrade cmake
      if [[ "${XCSF_PYLIB}" == "ON" ]]; then
        brew install python || brew upgrade python
        brew install boost-python3
      fi
    fi
    cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DXCSF_PYLIB="$XCSF_PYLIB" ..
  - make
